language: php

php:
  - 5.2
  - 5.3
  - 5.4

before_script:
  - wget http://pecl.php.net/get/memcached-2.1.0.tgz
  - tar -xzf memcached-2.1.0.tgz
  - cd memcached-2.1.0 && phpize && ./configure && make && sudo make install
  - echo "extension=memcached.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
